### ISSUE TITLE
Empty Filter.

### ISSUE THREAD

**Issue by xembill** [quintana-dev/sortboard#3]
Hi there! 
thanks for your code.. thats awesome! 
anyway; 
I need show an message if data filter have null? how can ı do it ? Please remind me. Thanks Again. 
Hi From Turkey :)

**Comment by joseluisq** [comment]
Hi,
Thanks for your feedback.
Yeah It's true this needed a support for empty filters. Now I published the new version with this improvement.

Example the `filterComplete( matches )` callback was updated, now support a single param (`matches`) it always should be an Array with `HTMLElements` matched or an empty Array if otherwise.

```js
...

filterComplete: function (matches)  {
  if (matches.length > 0) {
    // Not empty
  } else {
    // Empty
  }
}

...
```

Regards.
